# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vectolite',
                'doc_host': 'https://koaning.github.io',
                'git_url': 'https://github.com/koaning/vectolite',
                'lib_path': 'vectolite'},
  'syms': { 'vectolite.core': { 'vectolite.core.VectoLite': ('core.html#vectolite', 'vectolite/core.py'),
                                'vectolite.core.VectoLite.__init__': ('core.html#vectolite.__init__', 'vectolite/core.py'),
                                'vectolite.core.VectoLite.insert': ('core.html#vectolite.insert', 'vectolite/core.py'),
                                'vectolite.core.VectoLite.parse_item': ('core.html#vectolite.parse_item', 'vectolite/core.py'),
                                'vectolite.core.VectoLite.print_version': ('core.html#vectolite.print_version', 'vectolite/core.py'),
                                'vectolite.core.VectoLite.query': ('core.html#vectolite.query', 'vectolite/core.py'),
                                'vectolite.core.VectoLite.query_idx': ('core.html#vectolite.query_idx', 'vectolite/core.py'),
                                'vectolite.core.VectoLite.table_exists': ('core.html#vectolite.table_exists', 'vectolite/core.py'),
                                'vectolite.core.VectoLite.table_len': ('core.html#vectolite.table_len', 'vectolite/core.py')}}}
