# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vectoylite',
                'doc_host': 'https://koaning.github.io',
                'git_url': 'https://github.com/koaning/vectoylite',
                'lib_path': 'vectoylite'},
  'syms': { 'vectoylite.core': { 'vectoylite.core.VectoyLite': ('core.html#vectoylite', 'vectoylite/core.py'),
                                 'vectoylite.core.VectoyLite.__init__': ('core.html#vectoylite.__init__', 'vectoylite/core.py'),
                                 'vectoylite.core.VectoyLite.__len__': ('core.html#vectoylite.__len__', 'vectoylite/core.py'),
                                 'vectoylite.core.VectoyLite.table_exists': ('core.html#vectoylite.table_exists', 'vectoylite/core.py'),
                                 'vectoylite.core.serialize_f32': ('core.html#serialize_f32', 'vectoylite/core.py')}}}
